# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14cf94bf50796a7f3db85d6f5e7b3d7f4ecd6488f3aaab127e5694d6a4be700539099f39eb83685e351d5e8ac6590638f15c6c274b1937c9891e7edcc013d72f

test:
  secret_key_base: dbf46201e7c95bb8e9836dd1a093b8dbc2702a6371951496501e3e8ab591540faa71c5b309083eef7c6d27f011995aaafcd828843999f03498a473ff841a9269

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
